dataset: 'kkbox'

dataset_folder: 'data/kkbox/'

type_id: ['user', 'song', 'genre_ids', 'artist_name', 'composer']
# type_id_simple: ['u', 's', 'g', 'a', 'c']
type_id_simple: ['u', 's', 'a', 'c']
type2id: ['u':0, 's':1, 'a':2, 'c':4]

id2entity: 'id2entity.dict'
entity2id: 'entity2id.dict'
id2type: 'id2type.dict'
id2user: 'id2user.dict'
user2id: 'user2id.dict'
triples: 'triples.txt'

user_num: 34403
